name: {DRUVEN-LANDO-STARTER}
recipe: drupal10
config:
  php: 8.1
  webroot: web
  via: apache:2.4
  database: mariadb:10.6
services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://{DRUVEN-LANDO-STARTER}.lndo.site/"
  pma:
    type: phpmyadmin
proxy:
  pma:
    - pma.{DRUVEN-LANDO-STARTER}.lndo.site
tooling:
  project-install:
    service: appserver
    description: 'Prepares the project for its first use. Or reset the project to its initial state (Git not included in this reset).'
    cmd: echo "project-install"
  project-update:
    service: appserver
    description: 'Update project (Git not included in this reset).'
    cmd: echo "project-update"
